//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityModelContainer1 : DbContext
    {
        public EntityModelContainer1()
            : base("name=EntityModelContainer1")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Subcontractor> SubcontractorSet { get; set; }
        public virtual DbSet<Rate> RateSet { get; set; }
        public virtual DbSet<Admin> AdminSet { get; set; }
        public virtual DbSet<Client> ClientSet { get; set; }
        public virtual DbSet<Expert> ExpertSet { get; set; }
    }
}
